#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/home/tjrpirateking/projects/WritingAssistantApplication"

# Defaults chosen for your repo:
# - Prismo is skipped by default because it hung while generating compact packs.
# - Full Repomix pack is skipped by default because it produced ~292k tokens.
# - Docs-focused pack is generated by default.
RUN_PRISMO="${RUN_PRISMO:-0}"
RUN_FULL_REPOMIX="${RUN_FULL_REPOMIX:-0}"
RUN_GRAPHIFY_BUILD="${RUN_GRAPHIFY_BUILD:-0}"
INSTALL_ENTROLY="${INSTALL_ENTROLY:-0}"

PRISMO_TIMEOUT_SECONDS="${PRISMO_TIMEOUT_SECONDS:-300}"
GRAPHIFY_TIMEOUT_SECONDS="${GRAPHIFY_TIMEOUT_SECONDS:-600}"

echo "AI context/token tooling setup for:"
echo "$PROJECT_DIR"
echo

if [ ! -d "$PROJECT_DIR" ]; then
  echo "ERROR: Project directory not found: $PROJECT_DIR"
  exit 1
fi

cd "$PROJECT_DIR"

echo "Checking repo state..."
git status --short --branch || true
echo

echo "Checking required CLIs..."
command -v node >/dev/null 2>&1 || { echo "ERROR: node is required."; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "ERROR: npm is required."; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 is required."; exit 1; }

if ! command -v uv >/dev/null 2>&1 && ! command -v pipx >/dev/null 2>&1; then
  echo "WARNING: neither uv nor pipx found. Python tool installs will fall back to python3 -m pip --user where possible."
  echo "Recommended later: install uv or pipx so Python CLI tools stay isolated from the project venv."
fi

mkdir -p scripts ai_context .claude .cursor/rules

append_if_missing() {
  local file="$1"
  local line="$2"

  touch "$file"
  if ! grep -qxF "$line" "$file"; then
    printf '%s\n' "$line" >> "$file"
  fi
}

echo
echo "Adding generated AI context/graph outputs to .gitignore..."

append_if_missing .gitignore ""
append_if_missing .gitignore "# AI context/token tooling outputs"
append_if_missing .gitignore "ai_context/"
append_if_missing .gitignore ".prismo/"
append_if_missing .gitignore ".claudeignore.prismo-suggested"
append_if_missing .gitignore ".cursorignore.prismo-suggested"
append_if_missing .gitignore "prismo-optimized-CLAUDE.template.md"
append_if_missing .gitignore "repomix-output.*"
append_if_missing .gitignore "repomix-*.xml"
append_if_missing .gitignore "repomix-*.md"
append_if_missing .gitignore "graphify-out/"
append_if_missing .gitignore "graph.html"
append_if_missing .gitignore "GRAPH_REPORT.md"
append_if_missing .gitignore "graph.json"

echo
echo "Writing shared AI ignore files..."

cat > .repomixignore <<'REPOMIXIGNORE'
.git/
.venv*/
venv/
node_modules/
frontend/node_modules/
frontend/dist/
dist/
build/
__pycache__/
.pytest_cache/
.mypy_cache/
.ruff_cache/
.cache/
.DS_Store

# Local/generated project data
projects/
training/reports/
training/runs/
training/output/
training/checkpoints/
training/data/
*.jsonl
*.sqlite
*.db

# AI context and graph outputs
ai_context/
.prismo/
.claudeignore.prismo-suggested
.cursorignore.prismo-suggested
prismo-optimized-CLAUDE.template.md
graphify-out/
graph.html
GRAPH_REPORT.md
graph.json
repomix-output.*
repomix-*.xml
repomix-*.md

# Large/binary/non-source files
*.xlsx
*.xls
*.pdf
*.png
*.jpg
*.jpeg
*.webp
*.gif
*.mp3
*.wav
*.mp4
*.mov
*.zip
*.tar
*.gz
REPOMIXIGNORE

cp .repomixignore .claudeignore
cp .repomixignore .cursorignore

cat > .aiignore <<'AIIGNORE'
.git/
.venv*/
node_modules/
frontend/node_modules/
frontend/dist/
projects/
training/reports/
training/runs/
training/data/
*.jsonl
*.xlsx
*.pdf
*.png
*.jpg
*.jpeg
*.webp
ai_context/
.prismo/
graphify-out/
graph.html
GRAPH_REPORT.md
graph.json
AIIGNORE

echo
echo "Writing Repomix configs..."

cat > repomix.config.json <<'FULLREPOMIX'
{
  "output": {
    "filePath": "ai_context/repomix-workspace-context.xml",
    "style": "xml",
    "removeComments": false,
    "removeEmptyLines": false,
    "showLineNumbers": false,
    "topFilesLength": 20
  },
  "include": [
    "CLAUDE.md",
    "AGENTS.md",
    "README.md",
    "docs/master_plan.md",
    "docs/plan.md",
    "docs/roadmap/*.md",
    "backend/**/*.py",
    "frontend/src/**/*.{js,jsx,ts,tsx,css}",
    "tests/**/*.py"
  ],
  "ignore": {
    "useGitignore": true,
    "useDefaultPatterns": true,
    "customPatterns": [
      "projects/**",
      "training/reports/**",
      "training/runs/**",
      "training/data/**",
      "frontend/dist/**",
      "node_modules/**",
      ".venv*/**",
      "ai_context/**",
      ".prismo/**",
      "graphify-out/**",
      "graph.html",
      "GRAPH_REPORT.md",
      "graph.json",
      "*.jsonl",
      "*.xlsx",
      "*.pdf",
      "*.png",
      "*.jpg",
      "*.jpeg",
      "*.webp"
    ]
  },
  "security": {
    "enableSecurityCheck": true
  }
}
FULLREPOMIX

cat > repomix.workspace-docs.config.json <<'DOCSREPOMIX'
{
  "output": {
    "filePath": "ai_context/repomix-workspace-docs-context.xml",
    "style": "xml",
    "removeComments": false,
    "removeEmptyLines": false,
    "showLineNumbers": false,
    "topFilesLength": 30
  },
  "include": [
    "CLAUDE.md",
    "AGENTS.md",
    "README.md",
    "docs/master_plan.md",
    "docs/plan.md",
    "docs/roadmap/project_workspace_foundation_spec.md",
    "docs/roadmap/project_overview_page_spec.md",
    "docs/roadmap/project_selector_library_spec.md",
    "docs/roadmap/project_creation_flow_spec.md",
    "docs/roadmap/chapters_scenes_page_spec.md",
    "docs/roadmap/notes_materials_page_spec.md",
    "docs/roadmap/project_memory_canon_page_structure_spec.md",
    "docs/roadmap/omi_ideas_candidates_page_spec.md",
    "docs/roadmap/approved_characters_page_spec.md",
    "docs/roadmap/approved_locations_settings_page_spec.md",
    "docs/roadmap/approved_timeline_page_spec.md",
    "docs/roadmap/approved_plot_threads_page_spec.md",
    "docs/roadmap/project_memory_canon_storage_model.md",
    "docs/roadmap/writer_assistant_core_candidate_schemas.md",
    "docs/roadmap/omi_story_knowledge_candidate_expansion.md",
    "docs/roadmap/project_file_model.md",
    "docs/roadmap/task_backlog.md",
    "docs/roadmap/phase_map.md",
    "docs/roadmap/open_questions.md",
    "docs/roadmap/risk_register.md",
    "docs/roadmap/decision_log.md",
    "docs/roadmap/mvp_completion_test_matrix.md",
    "docs/roadmap/tooling_decisions.md"
  ],
  "ignore": {
    "useGitignore": true,
    "useDefaultPatterns": true,
    "customPatterns": [
      "backend/**",
      "frontend/**",
      "tests/**",
      "projects/**",
      "training/**",
      "node_modules/**",
      ".venv*/**",
      "ai_context/**",
      ".prismo/**",
      "graphify-out/**",
      "*.jsonl",
      "*.xlsx",
      "*.pdf",
      "*.png",
      "*.jpg",
      "*.jpeg",
      "*.webp"
    ]
  },
  "security": {
    "enableSecurityCheck": true
  }
}
DOCSREPOMIX

echo
echo "Running PrismoDev doctor..."
if [ "$RUN_PRISMO" = "1" ]; then
  timeout "$PRISMO_TIMEOUT_SECONDS"s npx --yes getprismo doctor || {
    echo "WARNING: PrismoDev doctor failed, timed out, or was interrupted."
    echo "Continuing with Repomix, CCE, Graphify, and LeanCTX."
  }
else
  echo "Skipping PrismoDev by default. Run with RUN_PRISMO=1 to enable it."
fi

echo
echo "Installing/checking Repomix..."
if npx --yes repomix@latest --version; then
  echo "Repomix is available."
else
  echo "WARNING: Repomix check failed."
fi

echo
echo "Generating docs-focused Repomix context..."
if npx --yes repomix@latest --config repomix.workspace-docs.config.json --compress --token-count-tree --output ai_context/repomix-workspace-docs-context.xml; then
  echo "Generated: ai_context/repomix-workspace-docs-context.xml"
else
  echo "WARNING: docs-focused Repomix context generation failed."
fi

if [ "$RUN_FULL_REPOMIX" = "1" ]; then
  echo
  echo "Generating full workspace Repomix context..."
  if npx --yes repomix@latest --config repomix.config.json --compress --token-count-tree --output ai_context/repomix-workspace-context.xml; then
    echo "Generated: ai_context/repomix-workspace-context.xml"
  else
    echo "WARNING: full Repomix context generation failed."
  fi
else
  echo
  echo "Skipping full workspace Repomix pack by default because it was ~292k tokens."
  echo "Run with RUN_FULL_REPOMIX=1 to generate it."
fi

echo
echo "Installing Code Context Engine if uv or pipx is available..."
if command -v uv >/dev/null 2>&1; then
  uv tool install "code-context-engine[local]" || true
elif command -v pipx >/dev/null 2>&1; then
  pipx install "code-context-engine[local]" || true
else
  echo "Skipping Code Context Engine install because uv/pipx is unavailable."
fi

if command -v cce >/dev/null 2>&1; then
  echo "Initializing Code Context Engine for supported agents..."
  cce init --agent all || true
  cce status || true
else
  echo "CCE command not found after install. You may need uv/pipx or a shell restart."
fi

echo
echo "Installing Graphify..."
if command -v uv >/dev/null 2>&1; then
  uv tool install graphifyy || uv tool upgrade graphifyy || true
elif command -v pipx >/dev/null 2>&1; then
  pipx install graphifyy || pipx upgrade graphifyy || true
else
  python3 -m pip install --user --upgrade graphifyy || true
  export PATH="$HOME/.local/bin:$PATH"
fi

export PATH="$HOME/.local/bin:$PATH"

if command -v graphify >/dev/null 2>&1; then
  echo "Registering Graphify for Claude Code, Codex, and Cursor..."
  graphify install --project || true
  graphify install --project --platform codex || true
  graphify cursor install || true

  if [ "$RUN_GRAPHIFY_BUILD" = "1" ]; then
    echo "Building initial Graphify knowledge graph..."
    timeout "$GRAPHIFY_TIMEOUT_SECONDS"s graphify . --no-viz || {
      echo "WARNING: Graphify graph generation failed or timed out."
      echo "Try manually later with: graphify . --no-viz"
    }
  else
    echo "Skipping Graphify graph build by default."
    echo "Run with RUN_GRAPHIFY_BUILD=1 to build the graph now."
  fi
else
  echo "Graphify command not found after install."
  echo "You may need to restart the shell or add ~/.local/bin to PATH."
fi

echo
echo "Installing LeanCTX..."
if ! command -v lean-ctx >/dev/null 2>&1; then
  if npm install -g lean-ctx-bin; then
    echo "LeanCTX installed through npm."
  else
    echo "npm global install failed. Trying universal installer..."
    curl -fsSL https://leanctx.com/install.sh | sh || true
    export PATH="$HOME/.local/bin:$PATH"
  fi
fi

export PATH="$HOME/.local/bin:$PATH"

if command -v lean-ctx >/dev/null 2>&1; then
  echo "Initializing LeanCTX for Claude Code, Codex, and Cursor..."
  lean-ctx init --agent claude || true
  lean-ctx init --agent codex || true
  lean-ctx init --agent cursor || true
  lean-ctx doctor || true
else
  echo "LeanCTX command not found after install."
  echo "You may need to restart the shell, or install manually:"
  echo "  npm install -g lean-ctx-bin"
  echo "  or"
  echo "  curl -fsSL https://leanctx.com/install.sh | sh"
fi

echo
echo "Optional Entroly install."
echo "Skipping by default because it is more invasive than Repomix/CCE/Graphify/LeanCTX."
if [ "$INSTALL_ENTROLY" = "1" ]; then
  if command -v uv >/dev/null 2>&1; then
    uv tool install entroly || true
  elif command -v pipx >/dev/null 2>&1; then
    pipx install entroly || true
  else
    python3 -m pip install --user entroly || true
  fi
fi

echo
echo "Writing helper script: scripts/generate_ai_context.sh"

cat > scripts/generate_ai_context.sh <<'GENCTX'
#!/usr/bin/env bash
set -euo pipefail

cd /home/tjrpirateking/projects/WritingAssistantApplication
mkdir -p ai_context

MODE="${1:-docs}"

if [ "$MODE" = "docs" ]; then
  echo "Generating docs-focused Repomix context..."
  npx --yes repomix@latest --config repomix.workspace-docs.config.json --compress --token-count-tree --output ai_context/repomix-workspace-docs-context.xml
  echo
  echo "Generated: ai_context/repomix-workspace-docs-context.xml"
  exit 0
fi

if [ "$MODE" = "full" ]; then
  echo "Generating full workspace Repomix context..."
  npx --yes repomix@latest --config repomix.config.json --compress --token-count-tree --output ai_context/repomix-workspace-context.xml
  echo
  echo "Generated: ai_context/repomix-workspace-context.xml"
  exit 0
fi

if [ "$MODE" = "task" ]; then
  shift || true

  if [ "$#" -eq 0 ]; then
    echo "ERROR: task mode requires file paths."
    echo "Example:"
    echo "  ./scripts/generate_ai_context.sh task docs/master_plan.md docs/plan.md docs/roadmap/task_backlog.md"
    exit 1
  fi

  echo "Generating task-specific Repomix context for:"
  printf '  %s\n' "$@"

  printf '%s\n' "$@" | npx --yes repomix@latest --stdin --compress --token-count-tree --output ai_context/repomix-current-task-context.xml

  echo
  echo "Generated: ai_context/repomix-current-task-context.xml"
  exit 0
fi

echo "Unknown mode: $MODE"
echo "Valid modes:"
echo "  docs"
echo "  full"
echo "  task <file1> <file2> ..."
exit 1
GENCTX

chmod +x scripts/generate_ai_context.sh

echo
echo "Writing helper script: scripts/context_health_check.sh"

cat > scripts/context_health_check.sh <<'HEALTH'
#!/usr/bin/env bash
set -euo pipefail

cd /home/tjrpirateking/projects/WritingAssistantApplication

echo "Git state:"
git status --short --branch --untracked-files=all || true

echo
echo "Large tracked files:"
git ls-files | xargs -r du -h 2>/dev/null | sort -h | tail -30 || true

echo
echo "AI context files:"
ls -lh ai_context 2>/dev/null || true

echo
echo "Ignored/generated Prismo files:"
ls -la .prismo 2>/dev/null || true
ls -lh .claudeignore.prismo-suggested .cursorignore.prismo-suggested prismo-optimized-CLAUDE.template.md 2>/dev/null || true

echo
echo "Graphify outputs:"
ls -lh graphify-out 2>/dev/null || true
ls -lh graph.html GRAPH_REPORT.md graph.json 2>/dev/null || true

echo
echo "Repomix docs token tree:"
npx --yes repomix@latest --config repomix.workspace-docs.config.json --token-count-tree --dry-run || true

echo
echo "CCE status:"
cce status || true

echo
echo "Graphify status:"
if command -v graphify >/dev/null 2>&1; then
  graphify --help >/dev/null 2>&1 && echo "Graphify installed." || true
else
  echo "Graphify not found."
fi

echo
echo "LeanCTX status:"
if command -v lean-ctx >/dev/null 2>&1; then
  lean-ctx doctor || true
  lean-ctx gain || true
else
  echo "LeanCTX not found."
fi
HEALTH

chmod +x scripts/context_health_check.sh

echo
echo "Installation/setup complete."
echo
echo "Next recommended commands:"
echo "  ./scripts/generate_ai_context.sh docs"
echo "  ./scripts/context_health_check.sh"
echo
echo "Optional commands:"
echo "  RUN_FULL_REPOMIX=1 ./scripts/install_ai_context_tools.sh"
echo "  RUN_GRAPHIFY_BUILD=1 ./scripts/install_ai_context_tools.sh"
echo "  RUN_PRISMO=1 ./scripts/install_ai_context_tools.sh"
echo "  INSTALL_ENTROLY=1 ./scripts/install_ai_context_tools.sh"
echo
echo "Claude Code optional plugin:"
echo "  /plugin marketplace add Madhan230205/token-reducer"
echo "  /plugin install token-reducer@Madhan230205-token-reducer"
echo
echo "Removed Caveman from this stack."
echo
echo "Important:"
echo "  Restart Claude Code, Codex, Cursor, and your shell after installing CCE, Graphify, or LeanCTX."
echo "  Review git status before committing any generated tool config files."
echo

git status --short --branch --untracked-files=all || true
